CREATE  TABLE IF NOT EXISTS CUSTOMER (
        CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        NAME CHAR(25) NOT NULL,
        ADDRESS CHAR(75) NOT NULL,
        PHONE CHAR(15) NOT NULL,
        EMAIL_ID CHAR(50) NOT NULL,
        PASSWORD CHAR(20) NOT NULL,
        TYPE CHAR(10) NOT NULL);

CREATE TABLE IF NOT EXISTS RECIPE(
        RECIPE_ID INTEGER PRIMARY KEY NOT NULL,
        NAME CHAR(50) NOT NULL,
        TYPE CHAR(20) NOT NULL,
        MAIN_INGREDIENT CHAR(20) NOT NULL,
        RECIPE_IMG TEXT,
        RECIPE_DESC TEXT NOT NULL	
        );


CREATE TABLE IF NOT EXISTS INGREDIENT(
        INGREDIENT_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        INGREDIENT_NAME CHAR(25) NOT NULL);

CREATE TABLE IF NOT EXISTS INGREDIENT_RECIPE(
        INGREDIENT_ID INTEGER,
        RECIPE_ID INTEGER,
        FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID) ON DELETE CASCADE,
        FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID) ON DELETE CASCADE,
        PRIMARY KEY (INGREDIENT_ID, RECIPE_ID));

CREATE TABLE IF NOT EXISTS SUPPLIER_RECIPE(
	CUSTOMER_ID INTEGER,
    RECIPE_ID INTEGER,
	ITEM_PRICE INTEGER,
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
        FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID) ON DELETE CASCADE,
        PRIMARY KEY (CUSTOMER_ID, RECIPE_ID));


INSERT INTO RECIPE VALUES(2,'Veg Burger','Veg','Potato', 'veg_burger.jpg', 'Burger');
INSERT INTO RECIPE VALUES(3,'Chicken Pasta','Non-veg','Chicken', 'pasta_nonveg.jpg', 'Pasta');
INSERT INTO RECIPE VALUES(4,'Fish Curry','Non-veg','Fish', 'fish_curry.jpg', 'Curry');
INSERT INTO RECIPE VALUES(5,'Fish Curry','Non-veg','Fish', 'fish_curry.jpg', 'Curry');
INSERT INTO RECIPE VALUES(6,'Veg Burger','Veg','Potato', 'veg_burger.jpg', 'Burger');
INSERT INTO RECIPE VALUES(7,'Mexican Chicken Burrito','Non-veg','Chicken', 'chipotle_chicken_burrito.jpg', 'Burrito');
INSERT INTO RECIPE VALUES(8,'Mexican Chicken Bowl','Non-veg','Chicken', 'chipotle_chicken_bowl.jpg', 'Bowl');
INSERT INTO RECIPE VALUES(9,'Fried Chicken Tikka','Non-veg','Chicken', 'chickentikka.jpg', 'Chicken');

INSERT INTO SUPPLIER_RECIPE VALUES(2,1,30);
INSERT INTO SUPPLIER_RECIPE VALUES(7,2,40);
INSERT INTO SUPPLIER_RECIPE VALUES(8,3,12);
INSERT INTO SUPPLIER_RECIPE VALUES(9,4,18);
INSERT INTO SUPPLIER_RECIPE VALUES(11,5,19);
INSERT INTO SUPPLIER_RECIPE VALUES(10,6,23);



CREATE  TABLE IF NOT EXISTS ORDER_DETAILS (
        ORDER_ID INT NOT NULL,
        CUSTOMER_ID INT NOT NULL,
        RECIPE_ID INT NOT NULL,
        ORDER_TYPE TEXT NOT NULL,
        ORDER_DATE TEXT NOT NULL,
        PRICE INT NOT NULL,
        QUANTITY INT NOT NULL,
        IS_PAID INT NOT NULL,
        ORDER_STATUS TEXT NOT NULL,
        DELIVERED_DATE TEXT,
        SUPPLIER_NAME TEXT,
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
        FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID) ON DELETE CASCADE,
        PRIMARY KEY( ORDER_ID, CUSTOMER_ID, RECIPE_ID));

CREATE  TABLE IF NOT EXISTS PAYMENT (
        PAYMENT_ID INT NOT NULL,
        CUSTOMER_ID INT NOT NULL,
        CARD_TYPE CHAR(10) NOT NULL,
        CARD_NUM CHAR(16) NOT NULL,
        EXPIRY_DATE char(5) NOT NULL,
        CVV char(3) NOT NULL,
        NAME CHAR(40) NOT NULL,
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
        PRIMARY KEY( PAYMENT_ID, CUSTOMER_ID));

